version: '3.1'
services:
  podbel_db:
    container_name: podbel_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: podbel_user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: podbel_db
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - podbel_db